server:
  error:
    include-message: always
    include-binding-errors: always
  port: ${PORT:8080}

spring:
  datasource:
        password: P@ssw0rd
        url: jdbc:postgresql://localhost:5432/spring-registration
        username: rickyjw
#    url: jdbc:postgresql://ec2-3-233-43-103.compute-1.amazonaws.com/d6mh8d64esef1h
#    username: iawwasoowyhmqu
#    password: 462c07e45a2b29247aae75baa3ba31b7b25246c61ef802a0f9b2dba08087f901

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

